import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ClerkProvider, SignedIn, SignedOut, SignInButton, UserButton} from "@clerk/nextjs";
import Link from "next/link";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider>
            <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-800`}
            >
            <header>
                <div className="text-white text-3xl bg-gray-800 flex justify-between items-center px-6 py-4">
                    <div className="flex space-x-4">
                        <Link href="/" className="hover:text-gray-300 underline duration-200">HomePage</Link>
                        <Link href="/record" className="hover:text-gray-300 underline duration-200">Voice to text</Link>
                    </div>
                    <div className="bg-green-600 px-4 py-2 rounded-lg">
                        <SignedOut>
                            <SignInButton/>
                        </SignedOut>
                        <SignedIn>
                            <UserButton />
                        </SignedIn>
                    </div>
                </div>

            </header>
            {children}
            </body>
            </html>
        </ClerkProvider>
    );
}
